✨ Add user instructions and regex option
nextcloud/registration pull request #259
Opened 2020-12-10 10:16 UTC by pxlfrk

Hey,

in our organization we use the registration app. As we want to inform our users about our name schema for the usernames (see #142 ) and also check (or force) the schema through an regex-function we added the code manually to the plugin.

These Changes get's reverted every update of the App, so i decided to create this PR & extended the code to be able to configure the parameter through the backend. I also implemented an option to add a text which is embedded in the verification email (see #243 ).

### Username Policy

Through the Settings panel a regular expression can be configured. If there is a regex configured the usernames get's validatet through the function and if the test fails, the user is prompted with the generic "please choose an appropiate username" error. I also implemented a syntax check in the settings panel, but i'm not sure how to deal with incorrect inputs. Looking forward to your input here.

| Screenshot | Description |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/39946364/101756279-2601da00-3ad6-11eb-8fe3-922f86f78cd7.png) | Regular expression field in the settings |
| ![image](https://user-images.githubusercontent.com/39946364/101756442-4e89d400-3ad6-11eb-8987-661a6e1192e9.png) | Error shown if the test fails |

### User instructions
Via the Settings panel the user can configure instructions for the user with additional informations. They will be shown to the user while creating his user account and/or embedded in the verification email.

| Screenshot | Description |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/39946364/101756311-2d28e800-3ad6-11eb-96e9-7f962f531c42.png) | settings parameter |
| ![image](https://user-images.githubusercontent.com/39946364/101756375-3d40c780-3ad6-11eb-8a75-0b80e94f9628.png) | user notification in the user-creation-screen |
| ![image](https://user-images.githubusercontent.com/39946364/101756535-68c3b200-3ad6-11eb-975f-c47e2402fced.png)) | embedded body-text in the verification email |

Looking forward to your review & feedback! 👍

2020-12-10 20:22 UTC, nickvergessen requested changes
Looks good in general. Thanks for sending the PR!

The only thing hurting a bit is that the hints can not be translated. So when you have users with more than 1 language, they will all see the same language. But I guess it's okay for now.

Can you fix the minor comments? Then we can put this in. 😎

2020-12-10 20:22 UTC, nickvergessen commented on lib/Controller/SettingsController.php
> +
```suggestion
			return new DataResponse([
				'data' => [
					'message' => $this->l10n->t('Invalid username policy regex'),
				],
				'status' => 'error',
			], Http::STATUS_BAD_REQUEST);
```

2020-12-10 20:22 UTC, nickvergessen commented on lib/Service/MailService.php
> +		};
```suggestion
 		if (!empty($email_verification_hint)) {
				$template->addBodyText($email_verification_hint);
		}; 
```

2020-12-10 20:22 UTC, nickvergessen commented on templates/admin.php
> +			<input type="text" id="username_policy_regex" name="username_policy_regex" value="<?php p($_['username_policy_regex']);?>" placeholder="/^[a-z-]+\.[a-z-]+$/">
```suggestion
			<input type="text" id="username_policy_regex" name="username_policy_regex" value="<?php p($_['username_policy_regex']);?>" placeholder="E.g.: /^[a-z-]+\.[a-z-]+$/">
```

2020-12-10 20:22 UTC, nickvergessen commented on templates/admin.php
> +	<h3><?php p($l->t('Username Policy')); ?></h3>
```suggestion
	<h3><?php p($l->t('Username policy')); ?></h3>
```

2020-12-10 20:22 UTC, nickvergessen commented on templates/admin.php
> +	<h3><?php p($l->t('User Instructions')); ?></h3>
```suggestion
	<h3><?php p($l->t('User instructions')); ?></h3>
```

2020-12-10 20:22 UTC, nickvergessen commented on templates/form/user.php
> +			<ul class="error">
```suggestion
			<ul class="msg">
```

2020-12-11 11:58 UTC, pxlfrk commented
> Looks good in general. Thanks for sending the PR!

Thanks @nickvergessen ! 👍 

> The only thing hurting a bit is that the hints can not be translated. So when you have users with more than 1 language, they will all see the same language. But I guess it's okay for now.

I totally understand your oint and also thought about this while adding the feature, but didn't have an alternative in mind. The only option to solve this right now would be to know which languages are in use and multiply the fields after that. But as the UI adapts to the system-language and the server doesn't know this (afaik) i don't see any chance of implementing this. I added a notice to the Settings-Panel that the configured text will be display to all users independent of their language.

> 
> Can you fix the minor comments? Then we can put this in. 😎
Sure, done that by writing this comment! 💯 

The php-cs check fails, but i'm not aware hot to solve them since php isn't my regular progamming language.

2020-12-11 16:22 UTC, nickvergessen commented on lib/Service/MailService.php
> +		};
```suggestion
		if (!empty($email_verification_hint)) {
			$template->addBodyText($email_verification_hint);
		};
```

This should fix the failing CS test

2020-12-11 16:39 UTC, nickvergessen commented
I can take it from here. Thanks again for the PR!

2020-12-14 10:51 UTC, nickvergessen commented
Merged via https://github.com/nextcloud/registration/commit/9e3b0b50e5cfa05aca13dca406f3184d3e2fda2e after fixing unit tests and adding new ones

2020-12-14 10:51 UTC, closed without merging

2020-12-14 13:42 UTC, nickvergessen commented
v0.6.0 released to the appstore

2020-12-14 15:40 UTC, pxlfrk commented
@nickvergessen thx for shipping. I just updatet the App. What's the procedure for updating the translation files? If the community over at transifex translated the newly introduced strings, do they only ship within a new release of the app (e.g. 0.61)? Just wan't to make sure i get the process right 💯

2020-12-14 16:02 UTC, nickvergessen commented
Oh right, should have waited a day or 2 before releasing. So yeah, will come with 0.6.1 I will check on friday if there was enough activity and otherwise after Xmas break in January.